rba fft 4
rba glmat 4
rba scarc_amg_fft_agg_l2_sm8 4
rba scarc_amg_fft_agg_l3_sm8 4
rba scarc_amg_fft_cub_l2_sm8 4
rba scarc_amg_fft_cub_l3_sm8 4
rba scarc_amg_fft_l2_sm8 4
rba scarc_amg_fft_l3_sm8 4
rba scarc_amg_ssor_agg_l2_sm8 4
rba scarc_amg_ssor_agg_l3_sm8 4
rba scarc_amg_ssor_cub_l2_sm8 4
rba scarc_amg_ssor_cub_l3_sm8 4
rba scarc_amg_ssor_l2_sm8 4
rba scarc_amg_ssor_l3_sm8 4
rba scarc_cgamg_fft_agg_l2_sm8 4
rba scarc_cgamg_fft_agg_l3_sm8 4
rba scarc_cgamg_fft_cub_l2_sm8 4
rba scarc_cgamg_fft_cub_l3_sm8 4
rba scarc_cgamg_ssor_agg_l2_sm8 4
rba scarc_cgamg_ssor_agg_l3_sm8 4
rba scarc_cgamg_ssor_cub_l2_sm8 4
rba scarc_cgamg_ssor_cub_l3_sm8 4
rba scarc_cgamg_ssor_l2_sm8 4
rba scarc_cgamg_ssor_l3_sm8 4
rba scarc_cggmg_fft_l2_sm8 4
rba scarc_cggmg_fft_l3_sm8 4
rba scarc_cggmg_ssor_agg_l2_sm8 4
rba scarc_cggmg_ssor_agg_l3_sm8 4
rba scarc_cggmg_ssor_cub_l2_sm8 4
rba scarc_cggmg_ssor_cub_l3_sm8 4
rba scarc_cggmg_ssor_l2_sm8 4
rba scarc_cggmg_ssor_l3_sm8 4
rba scarc_gmg_fft_l2_sm8 4
rba scarc_gmg_fft_l3_sm8 4
rba scarc_gmg_ssor_l2_sm8 4
rba scarc_gmg_ssor_l3_sm8 4
